//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predbiljezbe
    {
        public int Id { get; set; }
        public int IdSeminar { get; set; }
        public System.DateTime DatumPredbiljezbe { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string Mobitel { get; set; }
        public string Email { get; set; }
        public string Prihvacen_Odbijen { get; set; }
    
        public virtual Seminari Seminari { get; set; }
    }
}
