//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seminari()
        {
            this.Predbiljezbe = new HashSet<Predbiljezbe>();
        }
    
        public int Id { get; set; }
        public string NazivSeminara { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public string Opis { get; set; }
        public bool IsActive { get; set; }
        public bool Popunjen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predbiljezbe> Predbiljezbe { get; set; }
    }
}
