//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminariPredbiljezbeCount
    {
        public int IdProba { get; set; }
        public string NazivSeminara { get; set; }
        public int id { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public bool IsActive { get; set; }
        public string Opis { get; set; }
        public bool Popunjen { get; set; }
        public Nullable<int> count { get; set; }
    }
}
